In [2]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
df=pd.read_csv("c:\\Users\\User\\Downloads\\application_train.csv")
df.shape

(307511, 122)

In [3]:

null_values=(df.isna().sum()/df.shape[0])*100

In [4]:
df.columns

Index(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY',
       ...
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='str', length=122)

In [5]:
len(df.select_dtypes(include='int').columns)

41

In [6]:
len(df.select_dtypes(include='object').columns)

16

In [7]:

len(df.select_dtypes(include='float').columns)

65

In [8]:

df['NAME_CONTRACT_TYPE'].value_counts().index[0]

'Cash loans'

In [9]:
df['AMT_INCOME_TOTAL'].median()

np.float64(147150.0)

In [10]:
df.isna().sum().sum()

np.int64(9152465)

In [12]:
# Fill numeric columns with median
for col in df.select_dtypes(include=['int64', 'float64']).columns:
    df[col] = df[col].fillna(df[col].median())

# Fill object (categorical) columns with the most frequent value
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].fillna(df[col].value_counts().index[0])

In [13]:
df.isna().sum().sum()

np.int64(0)

In [14]:

df.select_dtypes(include='object').columns

Index(['NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY',
       'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE',
       'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'OCCUPATION_TYPE',
       'WEEKDAY_APPR_PROCESS_START', 'ORGANIZATION_TYPE', 'FONDKAPREMONT_MODE',
       'HOUSETYPE_MODE', 'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE'],
      dtype='str')

In [15]:
from sklearn.preprocessing import LabelEncoder

for i in df.select_dtypes(include='object').columns:
    df[i] = df[i].astype(str)
    le=LabelEncoder()
    le.fit(df[i])
    transformed_values=le.transform(df[i])
    df[i]=transformed_values

In [16]:
df.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,0,1,0,1,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,0,0,0,0,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,1,1,1,1,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,0,0,0,1,0,135000.0,312682.5,29686.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
4,100007,0,0,1,0,1,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0


In [17]:

df.columns

Index(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY',
       ...
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='str', length=122)

In [18]:

df['TARGET'].value_counts()

TARGET
0    282686
1     24825
Name: count, dtype: int64

In [19]:
##model building
df=df.sample(10000)
y=df['TARGET']
x=df.drop('TARGET',axis=1)

In [20]:

y.shape,x.shape

((10000,), (10000, 121))

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(8000, 121) (2000, 121) (8000,) (2000,)


In [22]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
dt = DecisionTreeClassifier()
dt.fit(x_train,y_train)
print(dt.predict(x_test)[0:10])
rf=RandomForestClassifier()
rf.fit(x_train,y_train)
print(rf.predict(x_test)[0:10])


[0 0 0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 0 0 0 0]


In [23]:
# model validation
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,dt.predict(x_test)))
print(confusion_matrix(y_test,rf.predict(x_test)))
print(accuracy_score(y_test,dt.predict(x_test)))
print(accuracy_score(y_test,rf.predict(x_test)))

[[1687  175]
 [ 118   20]]
[[1862    0]
 [ 138    0]]
0.8535
0.931
